apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kueue-viz-backend-read-access-binding
  namespace: system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kueue-viz-backend-read-access
subjects:
  - kind: ServiceAccount
    name: default
    namespace: system
