{{- if .Values.enableKueueViz }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ include "kueue.fullname" . }}-kueue-viz-backend'
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kueue-viz-backend
  template:
    metadata:
      labels:
        app: kueue-viz-backend
    spec:
      containers:
        - name: backend
          image: '{{ .Values.kueueViz.backend.image | default "us-central1-docker.pkg.dev/k8s-staging-images/kueue/kueue-viz-backend:main-latest" }}'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
{{- end }}
