{{- if .Values.enableKueueViz }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{ include "kueue.fullname" . }}-kueue-viz-frontend-ingress'
  namespace: '{{ .Release.Namespace }}'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - frontend.kueue-viz.local
      secretName: '{{ include "kueue.fullname" . }}-kueue-viz-tls-secret'
  rules:
    - host: frontend.kueue-viz.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: '{{ include "kueue.fullname" . }}-kueue-viz-frontend'
                port:
                  number: 8080
{{- end }}
