{{- if .Values.enableKueueViz }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "kueue.fullname" . }}-kueue-viz-frontend'
  namespace: '{{ .Release.Namespace }}'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: kueue-viz-frontend
{{- end }}
